# Generated by Django 2.2.3 on 2019-07-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPurbeurre2', '0002_productdb_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='manufacturing_places',
            field=models.TextField(),
        ),
    ]
